### ISSUE TITLE
Docker build tags

### ISSUE THREAD

**Issue by TheYkk** [passwall/passwall-server#107]
Passwal docker image should build with specific built tag example `passwall/passwall-server:1.1.0` for Backward Compatibility

**Comment by yakuter** [comment]
@TheYkk this is an important point. However I need an automation to create docker image with releases. There is a subject here  #104 . Can you help on creating docker image at releases?

**Comment by TheYkk** [comment]
Docker hub has this feature
![image](https://user-images.githubusercontent.com/21688838/83281966-93f14e80-a1e1-11ea-93f4-e69519e33e11.png)

**Comment by mrturkmen06** [comment]
Just to mention, [Goreleaser](https://goreleaser.com/customization/docker/) is able to handle both release and docker image at the same time. Of course, docker hub is also capable of handling it as well.

**Comment by yakuter** [comment]
Now docker-compose includes build tags and it is compatible with github stable branch releases. Thank you all for feedbacks and ideas.
