### ISSUE TITLE
SMTP Email configuration and functions needed

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-server#124]
**Is your feature request related to a problem? Please describe.**
The backend should send emails to admins or users in spesific situations. But for now we don't have any configuration or function to send emails

**Describe the solution you'd like**
For the begining we need SMTP configuration to send emails. Also we need easy to use email helper function to send email all over the backend.

Does anyone want to work on this?

**Comment by yusufpapurcu** [comment]
I do a little function for this and working fine.

Function : 
https://gist.github.com/yusufpapurcu/d846d48eb72be2397f0c32124f2fb19c

Example Usage : 
https://gist.github.com/yusufpapurcu/6cd5ff66c8699e0db6697e822c156fa1

**Comment by yakuter** [comment]
I will check it out, thank you @yusufpapurcu

**Comment by yakuter** [comment]
@yusufpapurcu thank you for your examples. Now I added email configuration to **config** and **SendMail** function to here:

https://github.com/passwall/passwall-server/blob/master/internal/app/send_email.go

Now we can send email from anywhere just like this:

`app.SendMail([]string{"erhan@passwall.io","hello@passwall.io",}, subject, body)`
