### ISSUE TITLE
Email verification feature needed

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-server#125]
This issue is related with  #124

**Is your feature request related to a problem? Please describe.**
Now we have multi user system. However we don't have any activation process for users.

**Describe the solution you'd like**
When users signup, system should send activation email to user. And when user click on activation link, system should activate user.

**Comment by yusufpapurcu** [comment]
I can do this issue.

**Comment by yakuter** [comment]
Hello @yusufpapurcu, thank you a lot. I am assigning you now. However can you wait just a little? I am addin a generic configuration and function to send emails. Then you can send activation email. 

By the way, how will you do this activation? I think we should talk beforehand just to be clear about the issue.

**Comment by yusufpapurcu** [comment]
I think we can store "Not Activated Accounts" into a array. And mark all data's with random string's. Like map[string]*models.User And user must go to .../activation/(random string) for activate his account. I tried this way. Worked but mail services don't render body because likely spam 😅. I think if sender and sended link will be ssl this not a problem.

**Comment by yakuter** [comment]
Well I just changed the title. I meant email verification when I say user activation :)

1. We need some database changes. We need to add **confirmation_code** (random md5 hash) and **email_verified_at** (datetime or NULL) fields to user table.

2. We need to add a new endpoint at /internal/api/auth.go like:
```go
func Confirm(s storage.Store) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
              // Confirmation codes
        }
}
```

3. router.go line should be like this:
```go
// router.go
authRouter.HandleFunc("/confirm/{email}/{code}", api.Confirm(r.store)).Methods(http.MethodPost)
```

4. We should add SendEmail to signup and send user confirmation code to user's email address.

5. User should click the link and confirm the email. The link should be like this:
https://vault.passwall.io/auth/confirm/erhan@passwall.io/5861139b4e9fd9e3a780617d7f4f8149

@yusufpapurcu is this ok with you?

**Comment by yusufpapurcu** [comment]
Yes it's ok. I'm starting work on this.

**Comment by yakuter** [comment]
Great. Assigned you now @yusufpapurcu

**Comment by yusufpapurcu** [comment]
Finished. Waiting for review :)
