### ISSUE TITLE
add more topic tags 

### ISSUE THREAD

**Issue by mrturkmencom** [passwall/passwall-server#128]
I have seen that repositories under pass-wall organization has no or few topic tags in repository description. It can have negative effects for users who need such a tool but finding difficulties to find it out. 

Examples; 

- [Passwall Extension](https://github.com/pass-wall/passwall-extension)

<img width="1045" alt="Screenshot 2020-06-21 at 11 42 09" src="https://user-images.githubusercontent.com/13614433/85220462-40bf8580-b3b4-11ea-8a91-88d947e125fa.png">

- [Passwall Desktop](https://github.com/pass-wall/passwall-desktop)

<img width="1041" alt="Screenshot 2020-06-21 at 11 41 51" src="https://user-images.githubusercontent.com/13614433/85220475-6f3d6080-b3b4-11ea-805e-3e8e2faf7769.png">

And others, repositories might not be seen in feed of Github, (when you do [explore](https://github.com/explore)) and it can reduce to have more contributor or user who are actually interested such a tool. 

I think, all repositories should contain related tags.

**Comment by yakuter** [comment]
I refactored all organization. Now we have only 2 repo and they are fine I think. Thank you @mrturkmencom
