### ISSUE TITLE
Better Encryption Handling 

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-server#131]
**Is your feature request related to a problem? Please describe.**
Some fields in objects stored encrypted and some of them not. We need a good way to handle it.

**Describe the solution you'd like**
We can use struct tags. For example we can say encryption:true/false in models. As an example:

```
type LoginDTO struct {
	ID       uint   `json:"id" encryption:"false"`
	Title    string `json:"title" encryption:"false"`
	URL      string `json:"url" encryption:"true"`
	Username string `json:"username" encryption:"true"`
	Password string `json:"password" encryption:"true"`
}
```

Then in DTO conversion functions in models, we can use reflect and convert fields which says encryption:"true".

Do anyone wants to work on this?

**Comment by recep** [comment]
I can do this issue.

**Comment by yakuter** [comment]
Great, I assigned you now.
