### ISSUE TITLE
talk proposal for github universe 2020

### ISSUE THREAD

**Issue by mrturkmencom** [passwall/passwall-server#143]
I got an email regarding to quite decent event which will be held on 8 December, (online) by Github. In my opinion, it is great opportunity to send a proposal to this talk about passwall-server and make the project more noticeable. It has different categories and I think, passwall-server project can fit at least one of them. I hope, it will going to happen, I just wanted to draw an attention about the event, if you are interested to become part of it. @yakuter 

[https://github.submittable.com/submit/493d84e1-b353-4aef-98fa-d21bf246d188/github-universe-2020-call-for-proposals](https://github.submittable.com/submit/493d84e1-b353-4aef-98fa-d21bf246d188/github-universe-2020-call-for-proposals)

**Comment by yakuter** [comment]
This is a great idea. Thank you so much @mrturkmencom I will send proposal 👍

**Comment by mrturkmencom** [comment]
Since deadline expired for the talk, I am closing the issue.
