### ISSUE TITLE
Unrelated email for user

### ISSUE THREAD

**Issue by emredipi** [passwall/passwall-server#150]
**Describe the bug**
Hello, I just signed up and I got two emails. One is for confirmation and other one is like "PassWall has new a user. ....".

**Expected behavior**
This email should have been sent to admin, not to user.

**Comment by yakuter** [comment]
Thank you @emredipi for your feedback. When I integrated sendgrid, I broke this email issue. For the fix we should change the following lines at **/internal/api/auth.go**
```
go app.SendMail(
	userDTO.Name,
	userDTO.Email,
	subject,
body)
```
with this:
```
go app.SendMail(
	viper.GetString("email.fromName"),
	viper.GetString("email.fromEmail"),
	subject,
body)
```

Can you handle this?

**Comment by emredipi** [comment]
Yes, I can handle. I would like to support.
