### ISSUE TITLE
Sqlite Database Support

### ISSUE THREAD

**Issue by fatihusta** [passwall/passwall-server#155]
**Sqlite database support for standalone use case**
I want to use passwall on my laptop without postgresql database server. Sqlite database would be very usable for this use case.
Postgresql needs too much effort for standalone use case.

**Comment by yakuter** [comment]
You are right about making this easy to use but unfortunately this is not possible because this server has a multi tenant structure based on postgresql schemas. So an sqlite support means changing all the structure.
