### ISSUE TITLE
Email Confirmation Feature

### ISSUE THREAD

**Issue by recep** [passwall/passwall-server#165]
User should verify email before signup step. In this way, user does not to verify after registration. 
User must not be able to register without verifying the email.

**Comment by fatihsezgin** [comment]
Anyone works on this issue? If it's not I can be a volunteer.

**Comment by recep** [comment]
Actually, this issue has already been done. You can check these endpoints:
https://github.com/passwall/passwall-server/blob/b260025a263543e611a1a2dc5cd8cf47b49733d6/internal/router/router.go#L113
https://github.com/passwall/passwall-server/blob/b260025a263543e611a1a2dc5cd8cf47b49733d6/internal/router/router.go#L114

**Comment by yakuter** [comment]
This is my mistake not to close the issue @fatihsezgin. Sorry :/
