### ISSUE TITLE
Multiple Signin

### ISSUE THREAD

**Issue by recep** [passwall/passwall-server#166]
If we delete the user's previous tokens when the user logs in, the user's sessions with other clients will be terminated.
https://github.com/passwall/passwall-server/blob/e1559905a0b02d325f822a1cf9402ff2e1b835c6/internal/api/auth.go#L219

**Comment by yakuter** [comment]
Fixed with v1.2.0 version

https://github.com/passwall/passwall-server/releases/tag/1.2.0
