### ISSUE TITLE
Can't run docker container

### ISSUE THREAD

**Issue by ikosa** [passwall/passwall-server#172]
I couldn't run a fresh installed docker container. 
This is the error seen. 

`could not open postgresql connection: dial tcp 127.0.0.1:5432: connect: connection refused`

**Comment by r1z4x** [comment]
I did the stable installation, there is no problem. The application cannot communicate with postgresql.
Can you share the details of `docker-compose logs`?

**Comment by ikosa** [comment]
Ok that's my bad.  I'm on Unraid and docker-compose not installed at default. And installing from community applications is not working.
Install docker-compose and install with it. Now it's up.
