### ISSUE TITLE
DB Connection Sslmode error

### ISSUE THREAD

**Issue by kahramanumut** [passwall/passwall-server#177]
I've tried to use with Heroku Postgresql service, but i occurred SSL Mode errors. Actually i don't know Golang, but i took a look at the codes and researched in stackoverflow, i realized problem in database.go DbConn Function. I changed sslmode from **disable** to **require** and it works.

I think, if sslmode would be parametric with config it would be better, such as port, dbname etc.

Kind regards.

**Comment by yakuter** [comment]
Hello @kahramanumut and @yakutozcan. Thanks to you, now you anyone can change db ssl mode is easily from config.yml
