### ISSUE TITLE
Nginx and SSL Certificate support via Docker-Compose

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-server#184]
Passwall Server has support for on-premise installation with Docker. To do this we have a docker-compose.yml file which has 2 services: **passwall-server** and **postgres**. However we need to add **Nginx** for reverse proxy. Also We need to easly generate SSL certificate with Let's Encrypt or user can add his/her own certificate via volumes.

I found this article which can give some ideas about the issue:
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-go-web-application-with-docker-and-nginx-on-ubuntu-18-04

Anyone wants to work on this?

**Comment by yakuter** [comment]
Great thank you @TheYkk

**Comment by TheYkk** [comment]
#189
