### ISSUE TITLE
Suggestions to CONTRIBUTING-TR.md

### ISSUE THREAD

**Issue by sadikkuzu** [passwall/passwall-server#193]
**Is your feature request related to a problem? Please describe.**

Update git remote address and update broken link.

**Describe the solution you'd like**

Change upstream git remote address in CONTRIBUTING-TR.md
`hoodiehq` -> `passwall`
as [done in CONTRIBUTING.md](https://github.com/passwall/passwall-server/commit/1205825dc98d4f0e57bd2270be5ad4cf8e7d76f3#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R93)

Change "şuradan" link of 
"Açık kaynak projeye nasıl katkıda bulunulabileceğini anlatan daha detaylı bir dokümana şuradan ulaşabilirsiniz."

https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github
->
https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github

**Comment by yakuter** [comment]
Thank you @sadikkuzu nice catch. Would you like to do it and send PR or I can handle it?

**Comment by sadikkuzu** [comment]
My pleasure @yakuter 🙏🏼

Sure, I can send a PR.

**Comment by yakuter** [comment]
Great thank you.👍
