### ISSUE TITLE
Run as a service on Homebrew

### ISSUE THREAD

**Issue by yakuter** [passwall/passwall-server#30]
To make it easier to install passwall-api, homebrew installation as a service is needed.

**Comment by patyogesh** [comment]
@yakuter I want to give this a shot. I will need to create a brew formula for this though, which needs git repository to host the formula. Would you be able to create a repository `passwall-brew` in this project?

**Comment by yakuter** [comment]
Great news. I created one now. Thank you.

https://github.com/pass-wall/passwall-brew

**Comment by yakuter** [comment]
Hi @patyogesh how is it going on the issue? Do you need anything I can provide?

**Comment by patyogesh** [comment]
@yakuter I have formula ready. Unable to push a PR though. Can you add me as a collaborator?

**Comment by patyogesh** [comment]
One issue I noticed while writing the formula is where to keep the `store/config.yml` file when passwall-server is installed using brew. In the current formula I am copying the default config file to `#{HOMEBREW_PREFIX}/Cellar/passwall-server/#{version}/`. Any thoughts?

**Comment by yakuter** [comment]
Hello @patyogesh. We need to connect not just config.yml but also store folder to #{HOMEBREW_PREFIX}/Cellar/passwall-server/#{version}/. Because we also have password.db for who uses SQL Lite and backup files passwall.bak. The folder you pointed is OK I think.

**Comment by patyogesh** [comment]
submitted [this](https://github.com/pass-wall/passwall-brew/pull/1) pull request.

**Comment by yakuter** [comment]
Now we user docker-compose to make server work at all environments. Closing the issue.
