### ISSUE TITLE
Important Security issues

### ISSUE THREAD

**Issue by anonrig** [passwall/passwall-server#43]
Hey there!

First of all congrats on the project. Even though this was a security focused project, I've had some issues with the codebase which I couldn't just do nothing about it. So, sorry about that :)

### Rate limiting
This seems to be a serious problem, since any person who has access to the login page, can brute force passwords. 
##### Possible solution
  - To use Redis and keep track of ip address of the user and limit if an offset is done. (This doesnt prevent user from attacking from different ip addresses. In that scenario having a timeout for account on invalid password requests can fix this vulnerability.)

### JWT Token Invalidation
In order to invalidate existing sessions in such a case that an environment is hijacked, there has to be token invalidation process in the passwall server.

### JWT Token information retrieval
Think of such a scenario: an attacker listened to local network traffic and saw a request with JWT Token and grabbed the token. Magically, on the backend we invalidated the JWT token, but since JWT Token includes user's username, now the attacker knows the username and can perform brute force attack with the username.
##### Possible solutions
  - Using user id (which should be a randomly generated UUID, to not reveal user count on the database) instead of username on JWT payload.

### Authentication transport
The password is sent to the backend using the HTTP layer. If no SSL is setup, (in local setup case), the password is sent without any encryption. This is open to MITM attacks.
##### Possible solutions
  - Use HMAC algorithm to verify whether the request is not manipulated using MITM attack. In such case, you need to exchange HMAC secret using Diffie Hellman algorithm to securely exchange keys. 
  - Use SSL pinning, and using a self signed certificate on the server side. This solves MITM attack scenarios. But you need to distribute SSL keys initial vectors to the clients.

### AES Passphrase storage
AES passphrase is either a static text or got through runtime. Any attack who has access to the environment objects can automatically decrypt all of your passwords.
##### Possible solutions
  - Storing AES is a tricky topic. 1Password solves this by having a master password (likely to be 10+ characters) and decrypting AES passphrase on runtime and using that decrypted AES passphrase to decrypt encrypted passwords on the database.
 
### Password store request
Referencing from: https://github.com/pass-wall/passwall-web/blob/master/pages/index.js#L37
```javascript
await fetch('/logins/', { method: 'POST', body: JSON.stringify(values) })
```
This is wrong in some many ways. Password shouldn't be sent to the server in plain text.

### SQL Injection
Title says it all.

Hope this feedback helps!

**Comment by yakuter** [comment]
Thank you for great analysis. I am fixing all issues one by one. For now:
- Added rate limiter
- Added middleware against XSS
- Using Gorm database package to prevent SQL injections.
- HMAC is on the way.
- Talked with client authors for better data (password) transportation between client and server.

I am keeping this issue open to complete the list.

**Comment by yakuter** [comment]
Now there is end to end encryption and both client and server has so many security protections. So I am closing this repo now.
