### ISSUE TITLE
Go Report card reports few linter errors

### ISSUE THREAD

**Issue by patyogesh** [passwall/passwall-server#93]
https://goreportcard.com/report/github.com/pass-wall/passwall-server

I have a fix for this. Need collaborator permission to submit a pull request.

**Comment by yakuter** [comment]
Hello @patyogesh that should be great.

**Comment by patyogesh** [comment]
@yakuter Unable to push my local branch.
```
ERROR: Permission to pass-wall/passwall-server.git denied to patyogesh

fatal: Could not read from remote repository.
```

**Comment by patyogesh** [comment]
@yakuter can you add me as a collaborator?

**Comment by mrturkmen06** [comment]
@patyogesh, I guess, you are trying to push changes directly into main repository, you do not need to have direct access to repo, first, fork the repo and implement changes in your account, then create pull request afterwards. I hope, [this guide](https://help.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) can aid you to create pull request for the changes that you desire to make.

**Comment by yakuter** [comment]
Thank you Ahmet. I think this is the problem.

**Comment by furkanbegen** [comment]
Should we close this issue and create a new issue for "go lint" errors because only go lint errors remain or we continue this issue and fix remaining "go lint" issues

**Comment by yakuter** [comment]
@furkanbegen you are right about this. PassWall server should pass all linter errors defined in this package:
https://github.com/golangci/golangci-lint

Can you open an issue for this? There is too much to do for this. We should work together.

**Comment by furkanbegen** [comment]
@yakuter opened a new issue #149
